// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyBXPKlKqAvj_27OVVcb1hU2in21azGrOuM',
    appId: '1:322774195223:android:abeddd9ab16c75fb311052',
    messagingSenderId: '322774195223',
    projectId: 'belajar-flutter-mpl',
    storageBucket: 'belajar-flutter-mpl.firebasestorage.app',
  );

  static const FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyBrG4ZXcRUw3lnCpafQ-8gg8y5T-Rx752g',
    appId: '1:322774195223:ios:54b3c971faf39640311052',
    messagingSenderId: '322774195223',
    projectId: 'belajar-flutter-mpl',
    storageBucket: 'belajar-flutter-mpl.firebasestorage.app',
    iosBundleId: 'com.example.freecodecampTutorialFlutter',
  );
}
